language: php
php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --dev

script:
  - ./vendor/bin/phpunit -c ./test
  - ./bin/check-cs.sh
  
notifications:
  irc: "irc.freenode.org#roave"
  email: false
